apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: clinet-deployment-nginx-iperf-k8s
  name: clinet-deployment-nginx-iperf-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinet-tcp
  strategy: {}
  template:
    metadata:
      labels:
        app: clinet-tcp
    spec:
      containers:
      - image: soyokaze0125/my-nginx-iperf3-image:v4
        name: clinet
        resources: {}
        imagePullPolicy: Always
        tty: true
        # args: ["iperf3", "-s", "-p","80"]
        # args: ["qperf","--listen_port","5001"]
        args: ["bash"]

      nodeSelector:
        kubernetes.io/hostname: master1
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: clinet-service
  name: clinet-service
spec:
  ports:
  - name: "ipref"
    port: 5001
    protocol: TCP
    targetPort: 5001
    
  selector:
    app: clinet-tcp
  type: NodePort
status:
  loadBalancer: {}