apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    key: value
  name: sample
spec:
  containers:
  - image: soyokaze0125/net-client:v1
    name: sample
    resources: {}
    tty: true
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: net-client-worker02-pod-service
  name: net-client-worker02-pod-service
spec:
  ports:
  - name: "ipref"
    port: 5201
    protocol: TCP
    targetPort: 5201
  selector:
    app: net-client-worker02-pod
  type: NodePort
status:
  loadBalancer: {}